In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


LINEAR REGRESSION

In [55]:
import pandas as pd
import numpy as np

In [56]:
data = pd.read_csv("/content/diabetes.csv")
data.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0

In [57]:
X = data.iloc[:,1:2]
Y = data.iloc[:,-1]
print(X.head())
print(Y.head(2))

   Glucose
0      148
1       85
2      183
3       89
4      137
0    1
1    0
Name: Outcome, dtype: int64


In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=2)
x_train.head(3)

Glucose
501       84
371      118
634       92

In [59]:
class LinearRegression:
  def __init__(self):
    self.b=None
    self.m=None

  def fit(self,x_train,y_train):
    x_train = x_train.values.flatten()
    y_train = y_train.values.flatten()
    num = 0
    den = 0

    for i in range(x_train.shape[0]):
      num = num + ((x_train[i] - x_train.mean())*(y_train[i] - y_train.mean()))
      den = den + ((x_train[i] - x_train.mean()) * (x_train[i] - x_train.mean()))

    self.m = num / den
    self.b = y_train.mean() - (self.m * x_train.mean())
    print(self.m)
    print(self.b)

  def predict(self,x_test):
    x_test = x_test.values.flatten()
    print(x_test)
    return self.m * x_test + self.b

In [60]:
lr = LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
y_pred

0.007148874530597651
-0.5158455539187887
[ 88 129 102 123 144  98  88 175  73 163 120 108 193  95  44 152 193  95
 127 181 153 145 110 122  99  57 134 126 121 108 126 100  80  95 115 194
 103 140 129 101 108  95 100 112  79  99 124 102  91 139 180 105 109 151
 116 123 196 136 109  95 109 158 166 195 122 136 175  87 122 107  94  84
 144  89 106 147 128 107  94  90  79 114  67 107 154 103 105 106 106 134
  83 122  93  85 117 143 128 126 166  75 146 158 128  80 102  95 135  92
 111   0 105 120 148  93 115 168 106 106 109 113   0 121  83 126 137 148
 107 151 149  97 128 119 139  87 103 173 106 132 130 109 124 123 126 119
  74 111  61 145  98 106  83 132 137  73 124  95  94 184  73 162 106   0
  94  88 137 108  96 197 118  91 100 159 114 112  85  85 140 124 109 102
  84 105 179 125 101  88 108 155  99 132 115  75 133 181 136 124 138 131
 110  89 133 182 101  65 189 131 143 125 107 180 165  99 126 114  96  76
 114 125 167 196 189  99 111  94  97 173  87 105 162 115  92]


array([ 0.1132554 ,  0.40635926,  0.21333965,  0.36346601,  0.51359238,
        0.18474415,  0.1132554 ,  0.73520749,  0.00602229,  0.64942099,
        0.34201939,  0.2562329 ,  0.86388723,  0.16329753, -0.20129507,
        0.57078337,  0.86388723,  0.16329753,  0.39206151,  0.77810074,
        0.57793225,  0.52074125,  0.27053064,  0.35631714,  0.19189302,
       -0.10835971,  0.44210363,  0.38491264,  0.34916826,  0.2562329 ,
        0.38491264,  0.1990419 ,  0.05606441,  0.16329753,  0.30627502,
        0.87103611,  0.22048852,  0.48499688,  0.40635926,  0.20619077,
        0.2562329 ,  0.16329753,  0.1990419 ,  0.28482839,  0.04891553,
        0.19189302,  0.37061489,  0.21333965,  0.13470203,  0.47784801,
        0.77095186,  0.23478627,  0.26338177,  0.5636345 ,  0.31342389,
        0.36346601,  0.88533385,  0.45640138,  0.26338177,  0.16329753,
        0.26338177,  0.61367662,  0.67086762,  0.87818498,  0.35631714,
        0.45640138,  0.73520749,  0.10610653,  0.35631714,  0.24

In [61]:
y_pred_

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [62]:
y_test_=y_test.values.flatten()
y_test_

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [63]:
accuracy = np.sum(y_pred_ == y_test_) / len(y_test_)

print("Accuracy:", accuracy * 100)

Accuracy: 76.62337662337663


In [64]:
from sklearn.metrics import accuracy_score
y_pred_=(y_pred >= 0.5).astype(int)
accuracy_score(y_pred_,y_test) * 100

76.62337662337663